### ISSUE TITLE
Deployment: containers with the same tag don't trigger the deploy

### ISSUE THREAD

**Issue by diegolagospagopa** [pagopa/aks-microservice-chart-blueprint#66]
When you have a deployment with a container with the same tag name (e.g. latest).

The pod image is not downloaded, and you need to kill the pod to allow the re-creation.

**Comment by pasqualedevita** [comment]
I think that this is the expected behavior.

**Comment by diegolagospagopa** [comment]
Resolved with the flag forceRedeploy

https://github.com/pagopa/aks-microservice-chart-blueprint/blob/38e0f3fc10e524c823f9c5f562200685da526b0d/charts/microservice-chart/templates/deployments.yaml#L23
